- name: Install CUPS packages and drivers
  become: true
  apt:
    name:
      - cups
      - cups-bsd
      - printer-driver-brlaser
      - printer-driver-gutenprint
    state: present

- name: Ensure CUPS service is enabled
  become: true
  service:
    name: cups
    enabled: true
    state: started
