- name: Install CUPS packages
  become: true
  apt:
    name:
      - cups
      - cups-bsd
    state: present

- name: Ensure CUPS service is enabled
  become: true
  service:
    name: cups
    enabled: true
    state: started

- name: Discover printer via ippfind
  command: ippfind
  register: ipp_discovery
  changed_when: false

- name: Set IPP URI (assuming only one on that subnet)
  set_fact:
    printer_uri: "{{ ipp_discovery.stdout_lines[0] }}"

- name: Check if {{ printer_name }} printer is already configured
  command: lpstat -v {{ printer_name }}
  register: printer_exists
  ignore_errors: true
  changed_when: false

- name: Add IPP Everywhere printer using discovered URI
  when: printer_exists.rc != 0
  command: >
    lpadmin -p {{ printer_name }} -E -v {{ printer_uri }} -m everywhere
  notify: Restart cups
