- name: Deploy static IP configuration for eth0
  become: true
  template:
    src: eth0.network.j2
    dest: /etc/systemd/network/eth0.network
    mode: '0644'
  notify: Restart systemd-networkd

- name: Ensure systemd-networkd service is enabled
  become: true
  service:
    name: systemd-networkd
    enabled: true
    state: started

