<<<<<<< Updated upstream
- name: Install Brother HL3170CDW CUPS wrapper script
  become: true
  copy:
    src: cupswrapperhl3170cdw
    dest: /usr/lib/cups/filter/brother_lpdwrapper_hl3170cdw
    mode: '0755'

- name: Copy Brother HL3170CDW PPD to system
  become: true
=======
---
- name: Build brcupsconfpt1
  make:
    chdir: "{{ role_path }}/files/brcupsconfig"

- name: Ensure directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /opt/brother/Printers/hl3170cdw/cupswrapper
    - /usr/share/ppd/Brother
    - /usr/lib/cups/filter

- name: Install brcupsconfpt1
  copy:
    src: "{{ role_path }}/files/brcupsconfig/brcupsconfpt1"
    dest: /opt/brother/Printers/hl3170cdw/cupswrapper/brcupsconfpt1
    mode: '0755'

- name: Install CUPS and generic printer drivers
  apt:
    name:
      - cups
      - cups-bsd
      - printer-driver-brlaser
      - printer-driver-gutenprint
    state: present
    update_cache: yes

- name: Ensure CUPS service is enabled and started
  service:
    name: cups
    enabled: true
    state: started

- name: Copy Brother HL-3170CDW PPD file
>>>>>>> Stashed changes
  copy:
    src: HL3170CDW.ppd
    dest: "{{ printer_ppd_dest }}"
    owner: root
    group: root
    mode: '0644'

- name: Detect USB printer URI
  become: true
  command: lpinfo -v
  register: lpinfo_output

- name: Set USB printer URI
  set_fact:
    printer_usb_uri: >-
      {{ lpinfo_output.stdout_lines | select('match', '^direct usb://') | list | first | regex_replace('^direct ', '') }}

- name: Register HL3170CDW printer
  become: true
  command: >-
    lpadmin -p {{ printer_name }} -E
    -v {{ printer_usb_uri }}
    -P {{ printer_ppd_dest }}
  args:
    creates: "/etc/cups/ppd/{{ printer_name }}.ppd"
  notify: Restart cups

- name: Enable printer sharing
  become: true
  command: cupsctl --share-printers
  notify: Restart cups
